### ISSUE TITLE
Usage of experimental APIs

### ISSUE THREAD

**Issue by lukahartwig** [web-std/io#33]
Both the `blob` and the `stream` package use the not yet stable Blob and Web Streams API from Node. This leads to warnings when used with newer node versions as found in https://github.com/remix-run/remix/issues/1141

It seems unsafe to me to use these APIs yet so I would opt for removing them until they become stable.

**Comment by Gozala** [comment]
I understand those APIs are unstable, yet for my use cases it was fine to use those. Additionally some issues in those APIs were fixed and worked around here.

This may not be a right choice for remix, yet I'm not sure use of custom polyifils that were used prior would be a better alternative.

If you have specific suggestions please feel free to reopen and suggest them, otherwise I'm closing this.
