### ISSUE TITLE
Should be able to pass a URL to fetch

### ISSUE THREAD

**Issue by olizilla** [web-std/io#9]
The current typs require us to pass a string to @web-std/fetch as the resource parameter. In the browser you can pass a URL instance as the resource, as it defines a stringifier attribute for it's href property https://url.spec.whatwg.org/#idl-index

The typings here are leading us to write `fetch(urlInstance.toString())` which is unappealing.

https://github.com/web-std/io/blob/68e89a806cd195bffa85cc5a8485711905761376/fetch/%40types/index.d.ts#L119

**Comment by Gozala** [comment]
Types just followed TS built-in types for `fetch` API. I believe it does not recognize `stringifier` attribute because it's not a part of the public interface that can be typed and allowing anything with `toString` would be more error prone.

Best course of action would be to try and update ts built-in types to `URL|string|Request`.
